// The recorder that produces `fixtures/mvp-replay.json`. Skipped unless RECORD_FIXTURE=1.
//
//   RECORD_FIXTURE=1 npx vitest run test/determinism/record.test.ts
//
// Why a recorder exists at all, rather than a hand-written fixture: engine entity ids are minted
// from a counter that advances as the world runs, so "the Barracks" is `b8` if you order it at
// tick 141 and something else if you order it at tick 140. Hand-writing ids produces a fixture
// that hashes deterministically while every order in it silently fails — which is worse than no
// fixture, because it is green.
//
// So the SCENARIO is written here as intent ("select the colony ship", "put the workers on the
// nearest ore"), the recorder resolves it against a real run, and what lands in the fixture is a
// flat list of concrete ids and ticks. The fixture stays exactly what P1-T21 asks for — a recorded
// seed plus a command stream — and this file is how you re-record it after an engine sync.

import { writeFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { type Intent, checkPlacement } from "../../src/bridge/commands.js";
import { MVP_WORLD, WorldBridge } from "../../src/bridge/world.js";
import { STEP_SECONDS } from "../../src/app/loop.js";
import { FIXTURE_PATH, hashState } from "./replay.js";

const SEED = 20260814;
const TICKS = 1200;                   // 60 sim-seconds at 20 Hz — long enough for a Barracks
                                      // to finish AND put two Skiffs on the field, which is what
                                      // makes the fixture cover production rather than just orders.

const NOTE = "The MVP demo recorded as data: land on Helix Belt, deploy the colony ship, put the "
  + "colonists on the nearest ore seam, raise a Barracks, train Skiffs from it, then push them east "
  + "at the neighbour. Entity ids are the engine's own and depend on WHEN each order is issued, so "
  + "this file is generated by test/determinism/record.test.ts rather than hand-written. Regenerate "
  + "it only when the vendored engine ref changes, in its own commit, naming the new ref.";

const shouldRecord = process.env.RECORD_FIXTURE === "1";

describe.skipIf(!shouldRecord)("fixture recorder", () => {
  it("plays the MVP scenario and writes the fixture", () => {
    const bridge = new WorldBridge({ seed: SEED, worldId: MVP_WORLD });
    const script: Array<[number, Intent]> = [];
    const problems: string[] = [];

    const at = (tick: number, intent: Intent): void => {
      script.push([tick, intent]);
      bridge.enqueue(intent);
    };
    const own = (pred: (u: Unit) => boolean): Unit | undefined =>
      [...bridge.state.units.values()].find((u) => u.owner === "player" && pred(u));

    for (let tick = 0; tick < TICKS; tick++) {
      switch (tick) {
        case 1: {
          const ship = own((u) => u.type === "colonyship");
          expect(ship, "the Odyssey opening must seed a colony ship").toBeDefined();
          at(1, { kind: "select", ids: [ship!.id], additive: false });
          break;
        }
        case 2:
          at(2, { kind: "deploy" });
          break;
        case 20: {
          const workers = [...bridge.state.units.values()].filter((u) => u.owner === "player" && u.type === "worker");
          expect(workers.length, "deploy should have landed colonists").toBeGreaterThan(0);
          const cc = [...bridge.state.buildings.values()].find((b) => b.owner === "player" && b.type === "command")!;
          const ore = bridge.state.map.nodes
            .filter((n) => n.com === "ore")
            .sort((a, b) => Math.hypot(a.x - cc.x, a.y - cc.y) - Math.hypot(b.x - cc.x, b.y - cc.y))[0]!;
          at(20, { kind: "select", ids: workers.map((w) => w.id), additive: false });
          at(20, { kind: "gather", nodeId: ore.id, queue: false });
          break;
        }
        case 140: {
          const worker = own((u) => u.type === "worker")!;
          const spot = firstLegalSpot(bridge, worker);
          expect(spot, "no legal Barracks site near the base — the scenario cannot proceed").not.toBeNull();
          at(140, { kind: "select", ids: [worker.id], additive: false });
          at(140, { kind: "build", buildingType: "barracks", x: spot!.x, y: spot!.y });
          break;
        }
        case 560: {
          const barracks = [...bridge.state.buildings.values()]
            .find((b) => b.owner === "player" && b.type === "barracks");
          expect(barracks, "the Barracks should exist by tick 560").toBeDefined();
          expect(barracks!.constructing, "…and should have finished building").toBe(false);
          at(560, { kind: "select", ids: [barracks!.id], additive: false });
          at(560, { kind: "train", buildingId: barracks!.id, unitType: "skiff" });
          at(560, { kind: "train", buildingId: barracks!.id, unitType: "skiff" });
          break;
        }
        case 1000: {
          const skiffs = [...bridge.state.units.values()].filter((u) => u.owner === "player" && u.type === "skiff");
          expect(skiffs.length, "the Barracks should have produced Skiffs by tick 1000").toBeGreaterThan(0);
          at(1000, { kind: "select", ids: skiffs.map((s) => s.id), additive: false });
          at(1000, { kind: "move", x: 700, y: 500, queue: false });
          break;
        }
        case 1080:
          at(1080, { kind: "attackMove", x: 1100, y: 500, queue: false });
          break;
        case 1160:
          at(1160, { kind: "hold" });
          break;
        default:
          break;
      }

      bridge.step(STEP_SECONDS);
      const err = bridge.takeCommandError();
      if (err) problems.push(`tick ${tick}: ${err}`);
    }

    expect(problems, `the recorded scenario must not contain refused orders:\n  ${problems.join("\n  ")}`).toEqual([]);

    const fixture = {
      seed: SEED,
      world: MVP_WORLD,
      ticks: TICKS,
      note: NOTE,
      script,
      hash: hashState(bridge.state),
    };
    writeFileSync(FIXTURE_PATH, JSON.stringify(fixture, null, 2) + "\n");
    console.log(`determinism fixture written: ${script.length} orders, hash ${fixture.hash}`);
  });
});

/** The first buildable Barracks site near a worker, searched in a fixed order so it is repeatable. */
function firstLegalSpot(bridge: WorldBridge, worker: Unit): { x: number; y: number } | null {
  for (const distance of [70, 90, 110, 130]) {
    for (const [dx, dy] of [[1, 0], [0, 1], [-1, 0], [0, -1], [1, 1], [-1, -1]] as const) {
      const x = worker.x + dx * distance;
      const y = worker.y + dy * distance;
      if (checkPlacement(bridge.state, "barracks", x, y).valid) return { x, y };
    }
  }
  return null;
}
