// The recorder that produces `fixtures/mvp-replay.json`. Skipped unless RECORD_FIXTURE=1.
//
//   RECORD_FIXTURE=1 npx vitest run test/determinism/record.test.ts
//
// Why a recorder exists at all, rather than a hand-written fixture: engine entity ids are minted
// from a counter that advances as the world runs, so "the Barracks" is `b8` if you order it at
// tick 141 and something else if you order it at tick 140. Hand-writing ids produces a fixture
// that hashes deterministically while every order in it silently fails — which is worse than no
// fixture, because it is green.
//
// So the SCENARIO is written here as intent ("select the colony ship", "put the workers on the
// nearest ore"), the recorder resolves it against a real run, and what lands in the fixture is a
// flat list of concrete ids and ticks. The fixture stays exactly what P1-T21 asks for — a recorded
// seed plus a command stream — and this file is how you re-record it after an engine sync.

import { writeFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { type Intent, checkPlacement } from "../../src/bridge/commands.js";
import { MVP_WORLD, WorldBridge } from "../../src/bridge/world.js";
import { STEP_SECONDS } from "../../src/app/loop.js";
import { FIXTURE_PATH, hashState } from "./replay.js";

const SEED = 20260814;
const TICKS = 1400;                   // 70 sim-seconds at 20 Hz — long enough for a Barracks
                                      // to finish, put two Skiffs on the field, and then run the
                                      // Phase 2 economy orders, which is what makes the fixture
                                      // cover production and trade rather than just orders.

const NOTE = "The MVP demo recorded as data, plus Phase 2's economy orders: land on Helix Belt, "
  + "deploy the colony ship, put the colonists on the nearest ore seam, raise a Barracks, train "
  + "Skiffs from it, sell a lot of ore on the market, set the Barracks' logistics priority, pause "
  + "and resume it, start and cancel a recycle, then push the Skiffs east at the neighbour. Entity "
  + "ids are the engine's own and depend on WHEN each order is issued, so this file is generated by "
  + "test/determinism/record.test.ts rather than hand-written. Regenerate it only when the vendored "
  + "engine ref changes, in its own commit, naming the new ref.";

const shouldRecord = process.env.RECORD_FIXTURE === "1";

describe.skipIf(!shouldRecord)("fixture recorder", () => {
  it("plays the MVP scenario and writes the fixture", () => {
    const bridge = new WorldBridge({ seed: SEED, worldId: MVP_WORLD });
    const script: Array<[number, Intent]> = [];
    const problems: string[] = [];

    const at = (tick: number, intent: Intent): void => {
      script.push([tick, intent]);
      bridge.enqueue(intent);
    };
    const own = (pred: (u: Unit) => boolean): Unit | undefined =>
      [...bridge.state.units.values()].find((u) => u.owner === "player" && pred(u));

    for (let tick = 0; tick < TICKS; tick++) {
      switch (tick) {
        case 1: {
          const ship = own((u) => u.type === "colonyship");
          expect(ship, "the Odyssey opening must seed a colony ship").toBeDefined();
          at(1, { kind: "select", ids: [ship!.id], additive: false });
          break;
        }
        case 2:
          at(2, { kind: "deploy" });
          break;
        case 20: {
          const workers = [...bridge.state.units.values()].filter((u) => u.owner === "player" && u.type === "worker");
          expect(workers.length, "deploy should have landed colonists").toBeGreaterThan(0);
          const cc = [...bridge.state.buildings.values()].find((b) => b.owner === "player" && b.type === "command")!;
          const ore = bridge.state.map.nodes
            .filter((n) => n.com === "ore")
            .sort((a, b) => Math.hypot(a.x - cc.x, a.y - cc.y) - Math.hypot(b.x - cc.x, b.y - cc.y))[0]!;
          at(20, { kind: "select", ids: workers.map((w) => w.id), additive: false });
          at(20, { kind: "gather", nodeId: ore.id, queue: false });
          break;
        }
        case 140: {
          const worker = own((u) => u.type === "worker")!;
          const spot = firstLegalSpot(bridge, worker);
          expect(spot, "no legal Barracks site near the base — the scenario cannot proceed").not.toBeNull();
          at(140, { kind: "select", ids: [worker.id], additive: false });
          at(140, { kind: "build", buildingType: "barracks", x: spot!.x, y: spot!.y });
          break;
        }
        case 560: {
          const barracks = [...bridge.state.buildings.values()]
            .find((b) => b.owner === "player" && b.type === "barracks");
          expect(barracks, "the Barracks should exist by tick 560").toBeDefined();
          expect(barracks!.constructing, "…and should have finished building").toBe(false);
          at(560, { kind: "select", ids: [barracks!.id], additive: false });
          at(560, { kind: "train", buildingId: barracks!.id, unitType: "skiff" });
          at(560, { kind: "train", buildingId: barracks!.id, unitType: "skiff" });
          break;
        }
        // --- Phase 2's economy orders (P2-T19) ---------------------------------------------------
        //
        // Each one is a NEW intent path, and the point of putting them here is that the replay hash
        // then covers them: an economy command that silently stopped reaching the engine would
        // still leave the hash unchanged if the fixture never issued one.
        //
        // Research is deliberately absent, and the reason is worth writing down rather than
        // leaving as a gap. It needs a Datacenter (200 ore) AND crystals for the tech itself, and
        // the recorder cannot inject resources — the fixture records only a seed and a script, so
        // anything handed to the player here would not exist on replay and the hash would not
        // reproduce. Seventy seconds of one ore seam does not fund a Datacenter. Covering research
        // needs a longer scenario, not a special case.

        case 600: {
          // Trade moves galaxy credits, which live above the world — so this is also the one order
          // in the fixture that proves the galaxy reference reaches the engine intact.
          at(600, { kind: "trade", com: "ore", qty: 25, side: "sell" });
          break;
        }
        case 620:
          at(620, { kind: "logiPriority", buildingId: barracksId(bridge), priority: "high" });
          break;
        case 640:
          at(640, { kind: "pause", buildingId: barracksId(bridge), paused: true });
          break;
        case 700:
          at(700, { kind: "pause", buildingId: barracksId(bridge), paused: false });
          break;
        case 760:
          // Started and cancelled, so the Barracks survives to finish its Skiffs — the point is to
          // exercise both halves of the order, not to lose the building.
          at(760, { kind: "recycle", entityId: barracksId(bridge) });
          break;
        case 780:
          at(780, { kind: "cancelRecycle", entityId: barracksId(bridge) });
          break;

        case 1000: {
          const skiffs = [...bridge.state.units.values()].filter((u) => u.owner === "player" && u.type === "skiff");
          expect(skiffs.length, "the Barracks should have produced Skiffs by tick 1000").toBeGreaterThan(0);
          at(1000, { kind: "select", ids: skiffs.map((s) => s.id), additive: false });
          at(1000, { kind: "move", x: 700, y: 500, queue: false });
          break;
        }
        case 1080:
          at(1080, { kind: "attackMove", x: 1100, y: 500, queue: false });
          break;
        case 1160:
          at(1160, { kind: "hold" });
          break;
        case 1300:
          // A recycle that is NOT cancelled, and it is here for a measured reason. The pair at
          // 760/780 exercises both orders, but it cancels out: with `recycle` broken, `cancelRecycle`
          // becomes a no-op and the end state is byte-identical, so the hash would not move. Probed
          // by dropping each order from the fixture and replaying — `recycle` alone came back NOT
          // COVERED. This one leaves the Barracks recycling at the final tick, so the hash carries it.
          at(1300, { kind: "recycle", entityId: barracksId(bridge) });
          break;
        default:
          break;
      }

      bridge.step(STEP_SECONDS);
      const err = bridge.takeCommandError();
      if (err) problems.push(`tick ${tick}: ${err}`);
    }

    expect(problems, `the recorded scenario must not contain refused orders:\n  ${problems.join("\n  ")}`).toEqual([]);

    const fixture = {
      seed: SEED,
      world: MVP_WORLD,
      ticks: TICKS,
      note: NOTE,
      script,
      hash: hashState(bridge.state),
    };
    writeFileSync(FIXTURE_PATH, JSON.stringify(fixture, null, 2) + "\n");
    console.log(`determinism fixture written: ${script.length} orders, hash ${fixture.hash}`);
  });
});

/** The player's Barracks. Its id is the engine's own, which is why the scenario asks rather than names. */
function barracksId(bridge: WorldBridge): string {
  const barracks = [...bridge.state.buildings.values()]
    .find((b) => b.owner === "player" && b.type === "barracks");
  if (!barracks) throw new Error("the economy orders expect a Barracks to exist by now");
  return barracks.id;
}

/** The first buildable Barracks site near a worker, searched in a fixed order so it is repeatable. */
function firstLegalSpot(bridge: WorldBridge, worker: Unit): { x: number; y: number } | null {
  for (const distance of [70, 90, 110, 130]) {
    for (const [dx, dy] of [[1, 0], [0, 1], [-1, 0], [0, -1], [1, 1], [-1, -1]] as const) {
      const x = worker.x + dx * distance;
      const y = worker.y + dy * distance;
      if (checkPlacement(bridge.state, "barracks", x, y).valid) return { x, y };
    }
  }
  return null;
}
